"""FreeBSD target configuration templates for the YetiOS image."""

import json
import shlex

RC_CONF = """\
# YetiOS FreeBSD rc.conf
hostname="{hostname}"
ifconfig_DEFAULT="DHCP"
sshd_enable="NO"
rc_startmsgs="NO"
rc_info="NO"
root_rw_mount="NO"
tmpmfs="YES"
tmpsize="512m"
varmfs="YES"
varsize="512m"
mfs_type="tmpfs"
populate_var="YES"
cleanvar_enable="YES"
hostid_enable="NO"
gptboot_enable="NO"
kldxref_enable="NO"
savecore_enable="NO"
newsyslog_enable="NO"
update_motd="NO"
mixer_enable="NO"
cron_enable="NO"
sendmail_enable="NONE"
sendmail_submit_enable="NO"
sendmail_outbound_enable="NO"
sendmail_msp_queue_enable="NO"
yetios_snowcone_enable="NO"
"""

LOADER_CONF = """\
# YetiOS FreeBSD base-builder loader.conf
autoboot_delay="1"
beastie_disable="YES"
loader_menu="NONE"
loader_autoboot_show="NO"
loader_logo="none"
console="efi"
boot_mute="NO"
boot_mutemsgs="NO"
boot_verbose="NO"
verbose_loading="NO"
kern.consmute="0"
kernel="kernel"
module_path="/boot/kernel;/boot/modules"
ext2fs_load="YES"
vfs.root.mountfrom="ext2fs:/dev/gpt/yetios-root"
"""

YETIOS_LOADER_CONF = """\
# YetiOS FreeBSD loader.conf
autoboot_delay="-1"
beastie_disable="YES"
loader_menu="NONE"
loader_autoboot_show="NO"
loader_logo="none"
console="nullconsole"
boot_mute="YES"
boot_mutemsgs="YES"
boot_verbose="NO"
verbose_loading="NO"
kern.consmute="1"
kernel="kernel"
module_path="/boot/kernel;/boot/modules"
ext2fs_load="YES"
splash_bmp_load="YES"
bitmap_load="YES"
bitmap_type="splash_image_data"
bitmap_name="/boot/yetios-black.bmp"
splash="/boot/images/yetios-black.png"
shutdown_splash="/boot/images/yetios-black.png"
vfs.root.mountfrom="ext2fs:/dev/gpt/yetios-root"
"""

FSTAB = """\
# YetiOS FreeBSD fstab
# The ext2 root is built by Linux tools and mounted read-only after first boot.
# Runtime write-heavy paths are memory-backed to avoid FreeBSD ext2 metadata
# corruption after abrupt VM power-offs.
/dev/gpt/yetios-root  /           ext2fs  ro,noatime  0 0
/dev/gpt/yetios-esp   /boot/efi   msdosfs rw,noatime,noauto 0 0
/dev/gpt/yetios-local /usr/local  ufs     rw,noatime,noauto 0 0
tmpfs                 /home       tmpfs   rw,mode=0755 0 0
/dev/gpt/yetios-swap  none        swap    sw          0 0
"""

LOADER_ENV = """\
currdev=disk0p1:
loaddev=disk0p1:
autoboot_delay=-1
beastie_disable=YES
loader_menu=NONE
loader_autoboot_show=NO
loader_logo=none
console=nullconsole
boot_mute=YES
boot_mutemsgs=YES
boot_verbose=NO
verbose_loading=NO
kern.consmute=1
kernel=kernel
module_path=/boot/kernel;/boot/modules
ext2fs_load=YES
splash_bmp_load=YES
bitmap_load=YES
bitmap_type=splash_image_data
bitmap_name=/boot/yetios-black.bmp
splash=/boot/images/yetios-black.png
shutdown_splash=/boot/images/yetios-black.png
vfs.root.mountfrom=ext2fs:/dev/gpt/yetios-root
"""

LIBRELDR_CONF = """\
# libreldr -- YetiOS FreeBSD boot configuration
# Generated by run.py.

timeout 5
default 0

title YetiOS
chain \\EFI\\freebsd\\loader.efi
options -m
"""

MOTD = """\
YetiOS FreeBSD alpha

Login:
  user: {user}
  password: {password}
  root password: {password}

Package management:
  Run: sudo pkg update
  Build YetiOS components inside FreeBSD with: ./assemble
  This alpha image ships a restricted YetiOS sudo helper for pkg and assemble.
"""

USER_PROFILE_APPEND = """\
# YetiOS alpha package-management helper.
PATH="/usr/local/bin:/usr/local/sbin:$PATH"
export PATH

pkg() {
    if [ "$(id -u)" -eq 0 ]; then
        command /usr/sbin/pkg "$@"
        return $?
    fi

    echo "pkg must run as root on this YetiOS alpha image."
    echo "Run: sudo pkg $*"
    return 1
}
"""

ASSEMBLE_HOME_WRAPPER_SH = """\
#!/bin/sh
# Convenience wrapper copied into the yetios user's tmpfs home.

if [ "$(id -u)" -eq 0 ]; then
    exec /usr/libexec/yetios/assemble "$@"
fi

exec /usr/bin/sudo /usr/libexec/yetios/assemble "$@"
"""

ASSEMBLE_SH_TEMPLATE = """\
#!/bin/sh
# YetiOS in-VM assembler.
#
# This must run inside the FreeBSD VM. The Artix/Linux host only prepares the
# FreeBSD base image and stages this script plus source trees.

set -eu

STAGED=/usr/src/yetios
SOURCES="$STAGED/sources"
PKG_LIST="$STAGED/desktop-packages.txt"
WORK=/usr/local/src/yetios-build
ESP=/boot/efi
LOCAL_DEV=/dev/gpt/yetios-local
ESP_DEV=/dev/gpt/yetios-esp
LOG=/var/log/yetios-assemble.log
ROOT_RW=0

JOBS="${YETIOS_JOBS:-__YETIOS_DEFAULT_JOBS__}"
if [ -z "$JOBS" ]; then
    JOBS="$(sysctl -n hw.ncpu 2>/dev/null || echo 2)"
fi

say() {
    printf '[*] %s\\n' "$*"
    printf '[*] %s\\n' "$*" >> "$LOG" 2>/dev/null || true
}

warn() {
    printf '[!] %s\\n' "$*" >&2
    printf '[!] %s\\n' "$*" >> "$LOG" 2>/dev/null || true
}

die() {
    printf '[x] %s\\n' "$*" >&2
    exit 1
}

run() {
    say "$*"
    "$@"
}

is_mounted() {
    mount | grep -q " on $1 "
}

mount_root_rw() {
    if [ "$ROOT_RW" = "1" ]; then
        return 0
    fi
    run mount -u -w /
    ROOT_RW=1
}

mount_root_ro() {
    if [ "$ROOT_RW" = "0" ]; then
        return 0
    fi
    sync
    mount -u -r / >/dev/null 2>&1 || true
    ROOT_RW=0
}

cleanup() {
    mount_root_ro
}

trap cleanup EXIT HUP INT TERM

require_root() {
    if [ "$(id -u)" -ne 0 ]; then
        die "Run this inside YetiOS as: sudo ./assemble"
    fi
}

ensure_local_storage() {
    mkdir -p /usr/local
    [ -e "$LOCAL_DEV" ] || die "Missing persistent local partition: $LOCAL_DEV"

    if ! fstyp "$LOCAL_DEV" >/dev/null 2>&1; then
        say "Formatting persistent YetiOS /usr/local on $LOCAL_DEV"
        run newfs -U -L yetios-local "$LOCAL_DEV"
    fi

    if ! is_mounted /usr/local; then
        run mount -t ufs "$LOCAL_DEV" /usr/local
    fi

    mkdir -p \\
        /usr/local/bin \\
        /usr/local/sbin \\
        /usr/local/share \\
        /usr/local/src \\
        /usr/local/var/cache/pkg \\
        /usr/local/var/db/pkg

    rm -rf /var/cache/pkg /var/db/pkg
    mkdir -p /var/cache /var/db
    ln -s /usr/local/var/cache/pkg /var/cache/pkg
    ln -s /usr/local/var/db/pkg /var/db/pkg
}

ensure_esp() {
    mkdir -p "$ESP"
    [ -e "$ESP_DEV" ] || die "Missing EFI system partition: $ESP_DEV"
    if ! is_mounted "$ESP"; then
        run mount -t msdosfs "$ESP_DEV" "$ESP"
    fi
}

install_packages() {
    [ -f "$PKG_LIST" ] || die "Missing package list: $PKG_LIST"

    run env ASSUME_ALWAYS_YES=yes pkg bootstrap -f
    packages="$(sed 's/#.*//' "$PKG_LIST" | awk 'NF {print $1}')"
    if [ -n "$packages" ]; then
        # shellcheck disable=SC2086
        run env ASSUME_ALWAYS_YES=yes pkg install -y $packages
    fi
}

copy_sources() {
    [ -d "$SOURCES" ] || die "Missing staged YetiOS sources: $SOURCES"
    rm -rf "$WORK"
    mkdir -p "$WORK"
    cp -R "$SOURCES/libreldr" "$WORK/libreldr"
    cp -R "$SOURCES/SnowCone" "$WORK/SnowCone"
    cp -R "$SOURCES/FrostedWeb" "$WORK/FrostedWeb"
    cp -R "$SOURCES/Moonshine" "$WORK/Moonshine"
    cp -R "$SOURCES/snowfall" "$WORK/snowfall"
}

patch_loader_status() {
    path="$1"
    [ -f "$path" ] || return 0
    if ! command -v perl >/dev/null 2>&1; then
        warn "perl is missing; cannot blank early FreeBSD loader status text"
        return 0
    fi
    perl -0pi -e 'for my $s ("Consoles: ","EFI console","    Reading loader env vars from %s","Setting currdev to %s","    Setting currdev to UEFI path %s","    Setting currdev to configured rootdev %s") { s/\\Q$s\\E/" " x length($s)/ge; }' "$path" || true
}

install_yetios_loader_config() {
    ensure_esp
    mkdir -p "$ESP/EFI/BOOT" "$ESP/EFI/freebsd" "$ESP/EFI/libreldr" "$ESP/boot"

    cp /boot/loader.efi "$ESP/EFI/freebsd/loader.efi"
    cp /boot/loader.efi "$ESP/boot/loader.efi"
    patch_loader_status "$ESP/EFI/freebsd/loader.efi"
    patch_loader_status "$ESP/boot/loader.efi"

    cat > "$ESP/boot/loader.conf" <<'YETIOS_LOADER_CONF'
__YETIOS_LOADER_CONF__
YETIOS_LOADER_CONF

    cat > "$ESP/EFI/freebsd/loader.env" <<'YETIOS_LOADER_ENV'
__YETIOS_LOADER_ENV__
YETIOS_LOADER_ENV

    cat > "$ESP/EFI/libreldr/libreldr.conf" <<'YETIOS_LIBRELDR_CONF'
__YETIOS_LIBRELDR_CONF__
YETIOS_LIBRELDR_CONF

    mount_root_rw
    cp "$ESP/boot/loader.conf" /boot/loader.conf
    mount_root_ro
}

build_libreldr() {
    say "Building libreldr inside FreeBSD"
    cd "$WORK/libreldr"
    gmake clean || true
    gmake \\
        ARCH=x86_64 \\
        EFI_ARCH=x86_64 \\
        BFD_ARCH=elf64-x86-64 \\
        EFIINC=/usr/local/include/efi \\
        EFILIB=/usr/local/lib \\
        CC=cc \\
        LD=ld.bfd

    ensure_esp
    install -m 0755 libreldr.efi "$ESP/EFI/BOOT/BOOTX64.EFI"
    install -m 0755 libreldr.efi "$ESP/EFI/libreldr/libreldr.efi"
}

build_snowcone() {
    say "Building SnowCone inside FreeBSD"
    cd "$WORK/SnowCone"
    gmake clean || true
    gmake freebsd

    mount_root_rw
    gmake install-freebsd
    sysrc yetios_snowcone_enable=YES >/dev/null
    mount_root_ro
}

build_frostedweb() {
    say "Building FrostedWeb inside FreeBSD"
    cd "$WORK/FrostedWeb"
    rm -rf build
    meson setup build --prefix=/usr/local
    ninja -j"$JOBS" -C build
    ninja -C build install
}

build_moonshine() {
    say "Building Moonshine inside FreeBSD with Wine's native Wayland driver"
    cd "$WORK/Moonshine"
    ./configure --enable-win64 --with-wayland --without-x
    gmake -j"$JOBS"
    gmake install
}

build_snowfall() {
    say "Checking SnowFall FreeBSD port status"
    cd "$WORK/snowfall"
    if [ ! -f src/drm_freebsd.c ] && [ ! -f src/input_freebsd.c ] && [ ! -f snowfall.freebsd.rc ]; then
        warn "SnowFall is still Linux/OpenRC/udev-based; skipping until its FreeBSD backend lands."
        return 0
    fi

    gmake clean || true
    gmake
    mount_root_rw
    install -d /usr/local/sbin /etc/rc.d /etc/pam.d
    install -m 0755 snowfall /usr/local/sbin/snowfall
    if [ -f snowfall.freebsd.rc ]; then
        install -m 0755 snowfall.freebsd.rc /etc/rc.d/snowfall
    fi
    if [ -f snowfall.pam ]; then
        install -m 0644 snowfall.pam /etc/pam.d/snowfall
    fi
    sysrc snowfall_enable=YES >/dev/null
    mount_root_ro
}

main() {
    require_root
    mkdir -p "$(dirname "$LOG")"
    : > "$LOG"

    say "YetiOS assemble starting inside FreeBSD"
    say "Log path: $LOG"
    say "Parallel jobs: $JOBS"
    ensure_local_storage
    ensure_esp
    install_packages
    copy_sources
    install_yetios_loader_config
    build_libreldr
    build_snowcone
    build_frostedweb
    build_moonshine
    build_snowfall
    sync
    say "YetiOS assemble complete. Reboot to use libreldr and SnowCone."
}

main "$@"
"""


def assemble_script(default_jobs: int) -> str:
    return (
        ASSEMBLE_SH_TEMPLATE
        .replace("__YETIOS_DEFAULT_JOBS__", str(default_jobs))
        .replace("__YETIOS_LOADER_CONF__", YETIOS_LOADER_CONF.rstrip())
        .replace("__YETIOS_LOADER_ENV__", LOADER_ENV.rstrip())
        .replace("__YETIOS_LIBRELDR_CONF__", LIBRELDR_CONF.rstrip())
    )


def limited_sudo_source(*, admin_user: str) -> str:
    q_admin_user = json.dumps(admin_user)
    return f"""\
/*
 * YetiOS restricted sudo helper.
 *
 * This is intentionally not a general sudo replacement. The alpha image only
 * needs the default admin user to bootstrap and update FreeBSD pkg from a
 * normal shell with: sudo pkg update
 */

#include <errno.h>
#include <grp.h>
#include <limits.h>
#include <pwd.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

#ifndef NGROUPS_MAX
#define NGROUPS_MAX 1024
#endif

#define YETIOS_ADMIN_USER {q_admin_user}
#define PKG_PATH "/usr/sbin/pkg"
#define ASSEMBLE_PATH "/usr/libexec/yetios/assemble"

static int user_is_wheel_member(gid_t gid)
{{
    struct group *wheel = getgrnam("wheel");
    gid_t groups[NGROUPS_MAX];
    int count;
    int i;

    if (wheel == NULL)
        return 0;
    if (gid == wheel->gr_gid)
        return 1;

    count = getgroups(NGROUPS_MAX, groups);
    if (count < 0)
        return 0;

    for (i = 0; i < count; i++) {{
        if (groups[i] == wheel->gr_gid)
            return 1;
    }}

    return 0;
}}

static int user_is_authorized(void)
{{
    uid_t uid = getuid();
    struct passwd *pw;

    if (uid == 0)
        return 1;

    pw = getpwuid(uid);
    if (pw == NULL)
        return 0;

    if (strcmp(pw->pw_name, YETIOS_ADMIN_USER) == 0)
        return 1;

    return user_is_wheel_member(pw->pw_gid);
}}

static int is_pkg_command(const char *arg)
{{
    return strcmp(arg, "pkg") == 0 || strcmp(arg, PKG_PATH) == 0;
}}

static int is_assemble_command(const char *arg)
{{
    const char *base;

    if (strcmp(arg, ASSEMBLE_PATH) == 0 || strcmp(arg, "/assemble") == 0)
        return 1;

    base = strrchr(arg, '/');
    base = base ? base + 1 : arg;
    return strcmp(base, "assemble") == 0;
}}

static void usage(FILE *out)
{{
    fprintf(out, "YetiOS alpha sudo: only pkg and assemble are allowed.\\n");
    fprintf(out, "Usage: sudo pkg <args>\\n");
    fprintf(out, "       sudo ./assemble\\n");
}}

int main(int argc, char **argv)
{{
    int command_index = 1;
    int child_argc;
    int i;
    int saved_errno;
    char **child_argv;
    const char *child_path;

    if (argc < 2) {{
        usage(stderr);
        return 64;
    }}

    if (strcmp(argv[1], "-h") == 0 || strcmp(argv[1], "--help") == 0 ||
        strcmp(argv[1], "-V") == 0) {{
        usage(stdout);
        return 0;
    }}

    if (strcmp(argv[1], "--") == 0)
        command_index = 2;

    if (command_index >= argc ||
        (!is_pkg_command(argv[command_index]) &&
         !is_assemble_command(argv[command_index]))) {{
        fprintf(stderr, "YetiOS alpha sudo only permits pkg and assemble.\\n");
        usage(stderr);
        return 126;
    }}

    if (!user_is_authorized()) {{
        fprintf(stderr, "YetiOS alpha sudo: user is not authorized.\\n");
        return 1;
    }}

    if (is_pkg_command(argv[command_index]))
        child_path = PKG_PATH;
    else
        child_path = ASSEMBLE_PATH;

    child_argc = argc - command_index;
    child_argv = calloc((size_t)child_argc + 1, sizeof(char *));
    if (child_argv == NULL) {{
        perror("calloc");
        return 1;
    }}

    child_argv[0] = (char *)child_path;
    for (i = 1; i < child_argc; i++)
        child_argv[i] = argv[command_index + i];
    child_argv[child_argc] = NULL;

    if (setgid(0) != 0 || setuid(0) != 0) {{
        perror("setuid");
        free(child_argv);
        return 1;
    }}

    execv(child_path, child_argv);
    saved_errno = errno;
    perror(child_path);
    free(child_argv);
    return saved_errno == ENOENT ? 127 : 126;
}}
"""


def firstboot_rc_local(*, user: str, password: str, timezone: str) -> str:
    q_user = shlex.quote(user)
    q_password = shlex.quote(password)
    q_timezone = shlex.quote(timezone)
    return f"""\
#!/bin/sh
# YetiOS first-boot setup for the FreeBSD base image.

set -eu

MARK=/etc/yetios-firstboot.done
ROOT_RW=0

mount_root_rw() {{
    if mount -u -w / >/dev/null 2>&1; then
        ROOT_RW=1
        return 0
    fi

    echo "YetiOS: could not make / writable for first-boot setup." >&2
    return 1
}}

mount_root_ro() {{
    sync
    mount -u -r / >/dev/null 2>&1 || true
    ROOT_RW=0
}}

cleanup_root_mount() {{
    if [ "$ROOT_RW" = "1" ]; then
        mount_root_ro
    fi
}}

trap cleanup_root_mount EXIT HUP INT TERM

install_yetios_sudo() {{
    if [ -x /usr/bin/sudo ]; then
        return 0
    fi

    if [ ! -f /usr/libexec/yetios-sudo.c ]; then
        echo "YetiOS: /usr/libexec/yetios-sudo.c is missing; sudo helper not installed." >&2
        return 0
    fi

    if ! command -v cc >/dev/null 2>&1; then
        echo "YetiOS: cc is missing; sudo helper not installed." >&2
        return 0
    fi

    if cc -O2 -Wall -Wextra -o /usr/bin/sudo /usr/libexec/yetios-sudo.c; then
        chown root:wheel /usr/bin/sudo || return 0
        chmod 4755 /usr/bin/sudo || return 0
    else
        echo "YetiOS: failed to build /usr/bin/sudo helper." >&2
    fi
}}

prepare_runtime_dirs() {{
    mkdir -p /usr/local
    if [ -e /dev/gpt/yetios-local ]; then
        if ! fstyp /dev/gpt/yetios-local >/dev/null 2>&1; then
            newfs -U -L yetios-local /dev/gpt/yetios-local >/dev/null
        fi
        if ! mount | grep -q " on /usr/local "; then
            mount -t ufs /dev/gpt/yetios-local /usr/local >/dev/null 2>&1 || true
        fi
    fi

    mkdir -p \\
        /home/{q_user} \\
        /usr/local/bin \\
        /usr/local/etc \\
        /usr/local/lib \\
        /usr/local/sbin \\
        /usr/local/share \\
        /usr/local/src \\
        /usr/local/var/cache/pkg \\
        /usr/local/var/db/pkg \\
        /tmp/yetios-snowcone \\
        /var/cache/pkg \\
        /var/db/pkg

    rm -rf /var/cache/pkg /var/db/pkg
    mkdir -p /var/cache /var/db
    ln -s /usr/local/var/cache/pkg /var/cache/pkg
    ln -s /usr/local/var/db/pkg /var/db/pkg

    if id -u {q_user} >/dev/null 2>&1; then
        if [ ! -f /home/{q_user}/.profile ] && [ -f /usr/share/skel/dot.profile ]; then
            cp /usr/share/skel/dot.profile /home/{q_user}/.profile
        fi
        if [ -f /usr/libexec/yetios/assemble-home-wrapper ]; then
            cp /usr/libexec/yetios/assemble-home-wrapper /home/{q_user}/assemble
            chmod 0755 /home/{q_user}/assemble
        fi
        chown {q_user}:wheel /home/{q_user} >/dev/null 2>&1 || true
        chown {q_user}:wheel /home/{q_user}/.profile >/dev/null 2>&1 || true
        chown {q_user}:wheel /home/{q_user}/assemble >/dev/null 2>&1 || true
    fi
    chmod 0755 /home/{q_user} /tmp/yetios-snowcone
}}

if [ ! -f "$MARK" ]; then
    mount_root_rw || exit 1

    if [ -f /usr/share/zoneinfo/{q_timezone} ]; then
        cp /usr/share/zoneinfo/{q_timezone} /etc/localtime
    fi

    if ! id -u {q_user} >/dev/null 2>&1; then
        printf '%s\\n' {q_password} | pw useradd {q_user} -m -s /bin/sh -G wheel,operator -h 0
    else
        printf '%s\\n' {q_password} | pw usermod {q_user} -h 0
    fi

    printf '%s\\n' {q_password} | pw usermod root -h 0

    install_yetios_sudo
    touch "$MARK"
    mount_root_ro
elif [ ! -x /usr/bin/sudo ]; then
    mount_root_rw && install_yetios_sudo && mount_root_ro
fi

prepare_runtime_dirs

exit 0
"""
