"""src/rootfs.py — templates for files & OpenRC services written into the
target root filesystem.

Pacman/mirror configuration, fstab, dhcpcd config, and the first-boot OpenRC
service scripts. The runtime package list lives in packages.txt at the repo
root, not here.
"""

# ---------------------------------------------------------------------------
# /etc/pacman.conf — Artix repos (OpenRC base) + Arch repos (wider package set)
#
# The Arch [extra]/[multilib] repos are usable only after artix-archlinux-support
# is installed and the archlinux keyring is populated (handled in stage 05).
# ---------------------------------------------------------------------------
PACMAN_CONF = """\
# YetiOS /etc/pacman.conf — generated by yeti-build.

[options]
HoldPkg            = pacman glibc
Architecture       = x86_64
CheckSpace
ParallelDownloads  = 5
SigLevel           = Required DatabaseOptional
LocalFileSigLevel  = Optional

# ---- Artix repositories (OpenRC, systemd-free base) ----
[system]
Include = /etc/pacman.d/mirrorlist

[world]
Include = /etc/pacman.d/mirrorlist

[galaxy]
Include = /etc/pacman.d/mirrorlist

# ---- Arch Linux repositories (broad package set; mixed in via
#      artix-archlinux-support) ----
[extra]
Include = /etc/pacman.d/mirrorlist-arch

[multilib]
Include = /etc/pacman.d/mirrorlist-arch
"""

# ---------------------------------------------------------------------------
# Mirror lists. `$repo` and `$arch` are pacman's own variables — left literal.
# ---------------------------------------------------------------------------
ARTIX_MIRRORLIST = "# YetiOS Artix mirror\nServer = {mirror}/$repo/os/$arch\n"
ARCH_MIRRORLIST = "# YetiOS Arch mirror\nServer = {mirror}/$repo/os/$arch\n"

# ---------------------------------------------------------------------------
# fstab — /boot is the FAT32 ESP.
# ---------------------------------------------------------------------------
FSTAB = """\
# YetiOS fstab — generated by yeti-build.
LABEL=yetios-root  /      ext4   defaults,noatime              0 1
LABEL=YETIOS-ESP   /boot  vfat   defaults,noatime,umask=0077   0 2
proc               /proc  proc   defaults                      0 0
"""

# ---------------------------------------------------------------------------
# First-boot OpenRC service that registers libreldr in UEFI NVRAM.
#
# Why this runs in the guest, not at build time:
#
#   * efibootmgr writes through efivarfs, which only exists when the kernel
#     was itself booted by UEFI firmware. The host's efivarfs (if any)
#     belongs to the host's NVRAM, not the VM's — writing it from the build
#     script would either fail or, worse, register YetiOS's loader on the
#     developer's own machine.
#
#   * The fallback path \\EFI\\BOOT\\BOOTX64.EFI ensures the VM boots even
#     before this service has ever run. After the first successful boot,
#     the firmware menu picks up a proper "LibreLoader (YetiOS)" entry.
#
# The script disables itself once registration succeeds so subsequent boots
# don't keep adding duplicates.
# ---------------------------------------------------------------------------
LIBRELDR_REGISTER_SERVICE = """\
#!/sbin/openrc-run

description="Register LibreLoader (libreldr) in UEFI NVRAM on first boot"

depend() {
    need localmount
    before local
}

start() {
    ebegin "Registering LibreLoader in UEFI boot menu"

    # Only meaningful on UEFI systems.
    if [ ! -d /sys/firmware/efi ]; then
        einfo "Not booted via UEFI; nothing to register."
        rc-update del libreldr-register default 2>/dev/null
        eend 0
        return 0
    fi

    if ! command -v efibootmgr >/dev/null 2>&1; then
        eerror "efibootmgr not installed"
        eend 1
        return 1
    fi

    # Find the disk + partition number that holds the ESP. /boot is the
    # ESP (see fstab). We resolve the mount → device → parent disk so the
    # script works on /dev/sda1, /dev/nvme0n1p1, /dev/vda1 alike.
    esp_dev="$(findmnt -n -o SOURCE /boot)"
    if [ -z "$esp_dev" ]; then
        eerror "Could not determine ESP device for /boot"
        eend 1
        return 1
    fi

    # PKNAME is the parent block device; PARTN is the partition number.
    esp_disk="/dev/$(lsblk -no PKNAME "$esp_dev")"
    esp_part="$(lsblk -no PARTN "$esp_dev" | tr -d ' ')"

    if [ -z "$esp_disk" ] || [ -z "$esp_part" ]; then
        eerror "Failed to resolve ESP disk/partition (dev=$esp_dev)"
        eend 1
        return 1
    fi

    # Skip if an entry with our label already exists.
    if efibootmgr | grep -q "LibreLoader (YetiOS)"; then
        einfo "LibreLoader entry already present; nothing to do."
        rc-update del libreldr-register default 2>/dev/null
        eend 0
        return 0
    fi

    # Single-quoted in bash, so each \\\\ in this Python literal becomes one
    # backslash on disk and is passed verbatim to efibootmgr.
    efibootmgr --create \\
        --disk "$esp_disk" \\
        --part "$esp_part" \\
        --label "LibreLoader (YetiOS)" \\
        --loader '\\EFI\\libreldr\\libreldr.efi'
    rc=$?

    if [ $rc -eq 0 ]; then
        einfo "Registered. Disabling first-boot service."
        rc-update del libreldr-register default 2>/dev/null
    fi
    eend $rc
}
"""

# ---------------------------------------------------------------------------
# dhcpcd configuration. Enabling dhcpcd as a global OpenRC daemon (stage 06 /
# postbuild) auto-discovers every wired interface (eth0, enp1s0, …); the
# virtio NIC in QEMU/KVM shows up as one of those.
# ---------------------------------------------------------------------------
DHCPCD_CONF = """\
# /etc/dhcpcd.conf — YetiOS defaults

# Don't touch the hostname — keep what we set at build time.
noipv4ll
nohook hostname

# Prefer wired interfaces, timeout quickly so boot isn't slow
# if no cable is plugged in.
timeout 15

# Allow Wine / general networking immediately.
option rapid_commit
option domain_name_servers, domain_name, domain_search
option classless_static_routes
option interface_mtu
"""

# ---------------------------------------------------------------------------
# First-boot Wine configuration service.
#
# On first login, Wine needs to initialise its prefix, download Mono/Gecko,
# and set up the desktop. This service runs once as the yeti user to do
# that initialization with network access available.
# ---------------------------------------------------------------------------
WINE_FIRSTBOOT_SERVICE = """\
#!/sbin/openrc-run

description="First-boot Wine prefix initialization (downloads Mono/Gecko)"

depend() {{
    need net
    after dhcpcd
}}

start() {{
    ebegin "Initializing Wine prefix for {yeti_user}"

    local wine_user="{yeti_user}"
    local wine_home="/home/$wine_user"

    # Skip if Wine prefix already exists and looks initialized
    if [ -f "$wine_home/.wine/system.reg" ]; then
        einfo "Wine prefix already initialized."
        rc-update del wine-firstboot default 2>/dev/null
        eend 0
        return 0
    fi

    # Initialize the Wine prefix — this triggers Mono/Gecko download
    # if the installers aren't already cached.
    su -l "$wine_user" -c "DISPLAY= WAYLAND_DISPLAY= wineboot --init" || true

    einfo "Wine prefix initialized. Disabling first-boot service."
    rc-update del wine-firstboot default 2>/dev/null
    eend 0
}}
"""

# ---------------------------------------------------------------------------
# Boot-time ALSA mixer initialization.
#
# On a fresh ALSA state the HDA codec frequently comes up with Master/PCM
# muted (or at zero). The PipeWire graph is then perfectly wired and frames
# flow, but the codec emits nothing — i.e. silence with no errors anywhere.
# This service brings the card to a sane, unmuted default BEFORE the
# graphical session (and therefore PipeWire / Moonshine) starts. It runs on
# every boot and persists the result. Safe no-op when no card is present.
#
# NOTE: plain shell braces here — this template is written verbatim (no
# str.format()), unlike WINE_FIRSTBOOT_SERVICE, so braces are NOT doubled.
# ---------------------------------------------------------------------------
ALSA_UNMUTE_SERVICE = """\
#!/sbin/openrc-run

description="Initialize and unmute the ALSA mixer for PipeWire output"

depend() {
    need localmount
}

start() {
    ebegin "Initializing ALSA mixer"

    if [ ! -e /proc/asound/card0 ]; then
        einfo "No ALSA card present; skipping."
        eend 0
        return 0
    fi

    # Bring the codec to its default (unmuted) state per the card's profile.
    alsactl init 2>/dev/null

    # Belt-and-suspenders: explicitly unmute and raise the controls the QEMU
    # HDA codec commonly exposes. Missing controls are ignored.
    for ctl in Master PCM Speaker Headphone Front; do
        amixer -c 0 -q sset "$ctl" unmute 2>/dev/null
        amixer -c 0 -q sset "$ctl" 100% 2>/dev/null
    done

    # Persist so the state survives reboots.
    alsactl store 2>/dev/null

    eend 0
}
"""
