"""Stage 1 — host sanity check.

Catches missing tools, wrong platform, no root, and no disk space.
No longer checks for WSLK-specific overlay files as those are now
handled by internal templates.
"""

from __future__ import annotations

import os
import sys

from .common import Config, err, have, ok, step_banner, warn


REQUIRED_HOST_TOOLS = [
    # Image + partition + mount
    "qemu-img", "parted", "mkfs.ext4", "mkfs.ext2", "losetup", "mount", "umount",
    # Download + extract stage3
    "wget", "tar", "xz",
    # Chroot + bootloader install
    "chroot", "extlinux",
]

# We removed the WSLK overlay files from here because they are now
# generated by src/templates.py
REQUIRED_OVERLAY_FILES = []


def run_stage(cfg: Config) -> None:
    step_banner("Stage 1 — Host sanity check")

    # 1. Platform Check
    if sys.platform != "linux":
        err("yeti-build must run on a Linux host (uses chroot + loop devices).")
        sys.exit(1)

    # 2. Privileges Check
    if os.geteuid() != 0:
        err("Run as root (or via sudo). Loop mounts and chroot require it.")
        sys.exit(1)

    # 3. Tools Check
    missing = [t for t in REQUIRED_HOST_TOOLS if not have(t)]
    if missing:
        err("Missing host tools: " + ", ".join(missing))
        err("On Debian/Ubuntu/Mint:")
        err("  apt install parted util-linux extlinux qemu-utils wget tar xz-utils")
        sys.exit(1)

    # 4. Disk Space Check
    needed_gb = cfg.img_size_gb + 5
    # Check parent directory if build/ doesn't exist yet
    parent = cfg.build_dir.parent if not cfg.build_dir.exists() else cfg.build_dir
    try:
        statvfs = os.statvfs(parent)
        free_gb = statvfs.f_bavail * statvfs.f_frsize / (1024 ** 3)
        if free_gb < needed_gb:
            err(f"Need ~{needed_gb} GB free in {parent}, have {free_gb:.1f} GB.")
            sys.exit(1)
    except FileNotFoundError:
        # If even the parent doesn't exist, we've got bigger problems
        err(f"Build directory path {parent} is invalid.")
        sys.exit(1)

    # 5. Overlay Check (Now Optional)
    # If the directory exists, we check it, but we no longer fail if it's empty
    # or missing since YetiOS now uses internal templates for its basic boot.
    if cfg.overlay_dir.is_dir():
        ok("yeti-overlay/ found (optional files will be used if present).")
    else:
        # Just a warning now, not an exit(1)
        warn(f"yeti-overlay/ not found at {cfg.overlay_dir}; using internal defaults.")

    ok(f"Linux host, root, all tools present, {free_gb:.1f} GB free.")