"""
src/templates.py — multi-line string templates rendered into the build.

Each template is a plain Python format string; callers use `.format(**kwargs)`.
"""

# ---------------------------------------------------------------------------
# /etc/portage/make.conf — Portage's main config file inside the target.
# ---------------------------------------------------------------------------
PORTAGE_MAKE_CONF = """\
# YetiOS make.conf — generated by yeti-build.

COMMON_FLAGS="-O2 -pipe"
CFLAGS="${{COMMON_FLAGS}}"
CXXFLAGS="${{COMMON_FLAGS}}"
FCFLAGS="${{COMMON_FLAGS}}"
FFLAGS="${{COMMON_FLAGS}}"

CHOST="x86_64-pc-linux-gnu"
MAKEOPTS="-j{jobs}"
EMERGE_DEFAULT_OPTS="--getbinpkg --binpkg-respect-use=y --jobs={jobs} --keep-going"

# Pull binary packages from Gentoo's official binhost when available.
FEATURES="getbinpkg binpkg-request-signature parallel-fetch parallel-install"
ACCEPT_KEYWORDS="amd64"
ACCEPT_LICENSE="*"

PORTAGE_TMPDIR="/var/tmp"
PORTDIR="/var/db/repos/gentoo"
DISTDIR="/var/cache/distfiles"
PKGDIR="/var/cache/binpkgs"
PORT_LOGDIR="/var/log/portage"

GENTOO_MIRRORS="https://distfiles.gentoo.org"

# USE flags: Minimal base for a Wayland environment.
USE="wayland vulkan opengl -X -gnome -kde -systemd elogind networkmanager pulseaudio"

# Video: Standard drivers for physical and virtual hardware.
VIDEO_CARDS="intel amdgpu radeonsi nouveau virtualbox vmware"
INPUT_DEVICES="libinput"

L10N="en-US"
LINGUAS="en_US en"
"""

# ---------------------------------------------------------------------------
# /etc/portage/binrepos.conf/gentoobinhost.conf — Gentoo's binhost.
# ---------------------------------------------------------------------------
PORTAGE_BINHOST_CONF = """\
[binhost]
priority = 9999
sync-uri = https://distfiles.gentoo.org/releases/amd64/binpackages/23.0/x86-64/
"""

# ---------------------------------------------------------------------------
# YetiOS Base Package List — emerged into the target.
# ---------------------------------------------------------------------------
YETI_PACKAGE_LIST = [
    # Kernel & Hardware
    "sys-kernel/gentoo-kernel-bin",
    "sys-kernel/linux-firmware",
    "media-libs/mesa",

    # Bootloader
    "sys-boot/syslinux",

    # Init + Userland basics
    "sys-apps/openrc",
    "app-shells/bash",
    "net-misc/dhcpcd",

    # Wayland stack (Libraries for development/core)
    "dev-libs/wayland",
    "dev-libs/wayland-protocols",
]

# ---------------------------------------------------------------------------
# fstab inside the target.
# ---------------------------------------------------------------------------
FSTAB = """\
# YetiOS fstab — generated by yeti-build.
LABEL=yetios-root  /       ext4   defaults,noatime  0 1
LABEL=yetios-boot  /boot   ext2   defaults,noatime  0 2
proc               /proc   proc   defaults          0 0
"""

# ---------------------------------------------------------------------------
# extlinux bootloader config.
# ---------------------------------------------------------------------------
EXTLINUX_CONF = """\
DEFAULT yetios
PROMPT 1
TIMEOUT 30

LABEL yetios
    MENU LABEL YetiOS
    LINUX /vmlinuz
    INITRD /initramfs.img
    APPEND root=LABEL=yetios-root ro quiet
"""