"""src/templates.py — multi-line string templates rendered into the build.
"""

# ---------------------------------------------------------------------------
# /etc/portage/make.conf
# ---------------------------------------------------------------------------
PORTAGE_MAKE_CONF = """\
# YetiOS make.conf — generated by yeti-build.

COMMON_FLAGS="-O2 -pipe"
CFLAGS="${{COMMON_FLAGS}}"
CXXFLAGS="${{COMMON_FLAGS}}"
FCFLAGS="${{COMMON_FLAGS}}"
FFLAGS="${{COMMON_FLAGS}}"

CHOST="x86_64-pc-linux-gnu"
MAKEOPTS="-j{jobs}"
EMERGE_DEFAULT_OPTS="--getbinpkg --binpkg-respect-use=y --jobs={jobs} --keep-going"

FEATURES="getbinpkg binpkg-request-signature parallel-fetch parallel-install"
ACCEPT_KEYWORDS="amd64"
ACCEPT_LICENSE="*"

PORTAGE_TMPDIR="/var/tmp"
PORTDIR="/var/db/repos/gentoo"
DISTDIR="/var/cache/distfiles"
PKGDIR="/var/cache/binpkgs"
PORT_LOGDIR="/var/log/portage"

GENTOO_MIRRORS="https://distfiles.gentoo.org"

USE="wayland vulkan opengl -X -gnome -kde -systemd elogind networkmanager pulseaudio"

VIDEO_CARDS="intel amdgpu radeonsi nouveau virtualbox vmware"
INPUT_DEVICES="libinput"

L10N="en-US"
LINGUAS="en_US en"
"""

# ---------------------------------------------------------------------------
# /etc/portage/binrepos.conf/gentoobinhost.conf
# ---------------------------------------------------------------------------
PORTAGE_BINHOST_CONF = """\
[binhost]
priority = 9999
sync-uri = https://distfiles.gentoo.org/releases/amd64/binpackages/23.0/x86-64/
"""

# ---------------------------------------------------------------------------
# YetiOS Base Package List (UEFI-only — no syslinux)
#
# Note on snowfall runtime deps: snowfall links against libdrm, libinput,
# cairo, libpam (sys-libs/pam), libxkbcommon, and libudev. Most of these
# are pulled in transitively by mesa + the Wayland stack + elogind, but
# we list them explicitly so a future change to those packages doesn't
# silently break the login manager at boot.
#
# Note on Moonshine (Wine fork) runtime deps: Moonshine is compiled on
# the build host (stage 07) and installed via DESTDIR into the rootfs.
# It links against Wayland, Vulkan, EGL, freetype, fontconfig, gnutls,
# dbus, ncurses, and unwind at runtime. These packages must be present
# in the rootfs or Moonshine will fail to launch. Most are already
# pulled by the Wayland/mesa stack, but we list the key ones explicitly.
# ---------------------------------------------------------------------------
YETI_PACKAGE_LIST = [
    # Kernel & Hardware
    "sys-kernel/gentoo-kernel-bin",
    "sys-kernel/linux-firmware",
    "media-libs/mesa",

    # UEFI: efibootmgr is invoked from the first-boot service to register
    # \\EFI\\libreldr\\libreldr.efi as a named entry in the firmware's
    # boot menu (so users see "LibreLoader" alongside any other OS).
    "sys-boot/efibootmgr",

    # Init + Userland basics
    "sys-apps/openrc",
    "app-shells/bash",
    "net-misc/dhcpcd",

    # Wayland stack
    "dev-libs/wayland",
    "dev-libs/wayland-protocols",
    "gui-libs/wlroots",             # Required by frostedglass compositor
    "x11-libs/pixman",              # Required by frostedglass compositor

    # Snowfall login manager runtime deps
    "x11-libs/cairo",
    "dev-libs/libinput",
    "x11-libs/libxkbcommon",
    "sys-libs/pam",
    # libdrm comes from x11-libs/libdrm (already a mesa dep, listed for clarity)
    "x11-libs/libdrm",
    # libudev comes from sys-apps/eudev (already a base dep, listed for clarity)
    "virtual/udev",

    # Moonshine (Wine fork) runtime deps — needed inside the rootfs
    # so Moonshine binaries installed by stage 07 can actually run.
    "media-libs/vulkan-loader",     # libvulkan.so for Vulkan rendering
    "media-libs/freetype",          # font rendering
    "media-libs/fontconfig",        # font configuration
    "net-libs/gnutls",              # TLS/crypto (schannel)
    "sys-apps/dbus",                # dynamic device support
    "sys-libs/ncurses",             # terminal / curses support
    "sys-libs/libunwind",           # exception handling / stack unwinding
    "dev-libs/glib",                # GLib (used by various Wine subsystems)
    "media-libs/libglvnd",          # EGL/OpenGL dispatch

    # Seat management — required by wlroots compositors (frostedglass)
    # to acquire DRM/input device access via libseat.
    "sys-auth/seatd",
]

# ---------------------------------------------------------------------------
# fstab — /boot is the FAT32 ESP.
# ---------------------------------------------------------------------------
FSTAB = """\
# YetiOS fstab — generated by yeti-build.
LABEL=yetios-root  /      ext4   defaults,noatime              0 1
LABEL=YETIOS-ESP   /boot  vfat   defaults,noatime,umask=0077   0 2
proc               /proc  proc   defaults                      0 0
"""

# ---------------------------------------------------------------------------
# First-boot OpenRC service that registers libreldr in UEFI NVRAM.
#
# Why this runs in the guest, not at build time:
#
#   * efibootmgr writes through efivarfs, which only exists when the kernel
#     was itself booted by UEFI firmware. The host's efivarfs (if any)
#     belongs to the host's NVRAM, not the VM's — writing it from the build
#     script would either fail or, worse, register YetiOS's loader on the
#     developer's own machine.
#
#   * The fallback path \\EFI\\BOOT\\BOOTX64.EFI ensures the VM boots even
#     before this service has ever run. After the first successful boot,
#     the firmware menu picks up a proper "LibreLoader (YetiOS)" entry.
#
# The script disables itself once registration succeeds so subsequent boots
# don't keep adding duplicates.
# ---------------------------------------------------------------------------
LIBRELDR_REGISTER_SERVICE = """\
#!/sbin/openrc-run

description="Register LibreLoader (libreldr) in UEFI NVRAM on first boot"

depend() {
    need localmount
    before local
}

start() {
    ebegin "Registering LibreLoader in UEFI boot menu"

    # Only meaningful on UEFI systems.
    if [ ! -d /sys/firmware/efi ]; then
        einfo "Not booted via UEFI; nothing to register."
        rc-update del libreldr-register default 2>/dev/null
        eend 0
        return 0
    fi

    if ! command -v efibootmgr >/dev/null 2>&1; then
        eerror "efibootmgr not installed"
        eend 1
        return 1
    fi

    # Find the disk + partition number that holds the ESP. /boot is the
    # ESP (see fstab). We resolve the mount → device → parent disk so the
    # script works on /dev/sda1, /dev/nvme0n1p1, /dev/vda1 alike.
    esp_dev="$(findmnt -n -o SOURCE /boot)"
    if [ -z "$esp_dev" ]; then
        eerror "Could not determine ESP device for /boot"
        eend 1
        return 1
    fi

    # PKNAME is the parent block device; PARTN is the partition number.
    esp_disk="/dev/$(lsblk -no PKNAME "$esp_dev")"
    esp_part="$(lsblk -no PARTN "$esp_dev" | tr -d ' ')"

    if [ -z "$esp_disk" ] || [ -z "$esp_part" ]; then
        eerror "Failed to resolve ESP disk/partition (dev=$esp_dev)"
        eend 1
        return 1
    fi

    # Skip if an entry with our label already exists.
    if efibootmgr | grep -q "LibreLoader (YetiOS)"; then
        einfo "LibreLoader entry already present; nothing to do."
        rc-update del libreldr-register default 2>/dev/null
        eend 0
        return 0
    fi

    # Single-quoted in bash, so each \\\\ in this Python literal becomes one
    # backslash on disk and is passed verbatim to efibootmgr.
    efibootmgr --create \\
        --disk "$esp_disk" \\
        --part "$esp_part" \\
        --label "LibreLoader (YetiOS)" \\
        --loader '\\EFI\\libreldr\\libreldr.efi'
    rc=$?

    if [ $rc -eq 0 ]; then
        einfo "Registered. Disabling first-boot service."
        rc-update del libreldr-register default 2>/dev/null
    fi
    eend $rc
}
"""