"""src/templates.py — multi-line string templates rendered into the build."""

# ---------------------------------------------------------------------------
# /etc/portage/make.conf
# ---------------------------------------------------------------------------
PORTAGE_MAKE_CONF = """\
# YetiOS make.conf — generated by yeti-build.

COMMON_FLAGS="-O2 -pipe"
CFLAGS="${{COMMON_FLAGS}}"
CXXFLAGS="${{COMMON_FLAGS}}"
FCFLAGS="${{COMMON_FLAGS}}"
FFLAGS="${{COMMON_FLAGS}}"

CHOST="x86_64-pc-linux-gnu"
MAKEOPTS="-j{jobs}"

# Keep the stage3's running interpreter (3.13) AND the binhost's target
# (3.14) both enabled through the build. Dropping 3.13 makes portage delete
# its own running modules mid-upgrade (ModuleNotFoundError: _SyncfsProcess).
# Single-target packages use 3.14; multi-target ones build for both.
PYTHON_TARGETS="python3_13 python3_14"
PYTHON_SINGLE_TARGET="python3_14"

EMERGE_DEFAULT_OPTS="--getbinpkg --binpkg-respect-use=y --jobs={jobs} --keep-going"

FEATURES="getbinpkg binpkg-request-signature parallel-fetch parallel-install"
ACCEPT_KEYWORDS="amd64"
ACCEPT_LICENSE="*"

PORTAGE_TMPDIR="/var/tmp"
PORTDIR="/var/db/repos/gentoo"
DISTDIR="/var/cache/distfiles"
PKGDIR="/var/cache/binpkgs"
PORT_LOGDIR="/var/log/portage"

GENTOO_MIRRORS="https://distfiles.gentoo.org"

# PipeWire audio-server USE flags:
#   sound-server : THE critical one. Makes PipeWire act as the system audio
#                  server so WirePlumber enumerates the HDA card into a real
#                  sink. With it OFF, PipeWire runs but creates ZERO audio
#                  devices — the long-hunted "no sink, total silence" bug
#                  (the ebuild even warns: "USE=sound-server is disabled!").
#   pulseaudio   : builds the pipewire-pulse daemon (PulseAudio-API shim) so
#                  pulse clients like Flatpak Firefox (cubeb) can play. NB:
#                  the daemon still has to be launched at session start —
#                  fg_audio.c spawns it alongside pipewire/wireplumber.
#   alsa         : pipewire-alsa (libasound plugin) so native ALSA apps route
#                  through PipeWire. Not required for output — the SPA alsa
#                  hardware backend is built regardless.
#   dbus         : libspa-dbus (device reservation; clears the libspa-dbus
#                  load warning; lets module-rt reach rtkit if installed).
USE="wayland vulkan opengl -X -gnome -kde -systemd elogind networkmanager pulseaudio pipewire alsa dbus sound-server"

VIDEO_CARDS="intel amdgpu radeonsi nouveau virtualbox vmware"
INPUT_DEVICES="libinput"

L10N="en-US"
LINGUAS="en_US en"
"""

# ---------------------------------------------------------------------------
# /etc/portage/binrepos.conf/gentoobinhost.conf
# ---------------------------------------------------------------------------
PORTAGE_BINHOST_CONF = """\
[binhost]
priority = 9999
sync-uri = https://distfiles.gentoo.org/releases/amd64/binpackages/23.0/x86-64/
"""

# ---------------------------------------------------------------------------
# YetiOS Base Package List (UEFI-only — no syslinux)
#
# Note on snowfall runtime deps: snowfall links against libdrm, libinput,
# cairo, libpam (sys-libs/pam), libxkbcommon, and libudev. Most of these
# are pulled in transitively by mesa + the Wayland stack + elogind, but
# we list them explicitly so a future change to those packages doesn't
# silently break the login manager at boot.
#
# Note on Moonshine (Wine fork) runtime deps: Moonshine is compiled on
# the build host (stage 07) and installed via DESTDIR into the rootfs.
# It links against Wayland, Vulkan, EGL, freetype, fontconfig, gnutls,
# dbus, ncurses, and unwind at runtime. These packages must be present
# in the rootfs or Moonshine will fail to launch. Most are already
# pulled by the Wayland/mesa stack, but we list the key ones explicitly.
# ---------------------------------------------------------------------------
YETI_PACKAGE_LIST = [
    # Kernel & Hardware
    "sys-kernel/gentoo-kernel-bin",
    "sys-kernel/linux-firmware",
    "media-libs/mesa",

    # UEFI: efibootmgr is invoked from the first-boot service to register
    # \\EFI\\libreldr\\libreldr.efi as a named entry in the firmware's
    # boot menu (so users see "LibreLoader" alongside any other OS).
    "sys-boot/efibootmgr",

    # Init + Userland basics
    "sys-apps/openrc",
    "app-shells/bash",

    # ---- Networking ----
    # dhcpcd for DHCP on wired interfaces (auto-configures eth0/ens*/enp*).
    # virtio NIC in QEMU/KVM appears as an enp* or eth* device.
    "net-misc/dhcpcd",

    # Wayland stack
    "dev-libs/wayland",
    "dev-libs/wayland-protocols",
    "gui-libs/wlroots",             # Required by frostedglass compositor
    "x11-libs/pixman",              # Required by frostedglass compositor

    # Snowfall login manager runtime deps
    "x11-libs/cairo",
    "dev-libs/libinput",
    "x11-libs/libxkbcommon",
    "sys-libs/pam",
    # libdrm comes from x11-libs/libdrm (already a mesa dep, listed for clarity)
    "x11-libs/libdrm",
    # libudev comes from sys-apps/eudev (already a base dep, listed for clarity)
    "virtual/udev",

    # Moonshine (Wine fork) runtime deps — needed inside the rootfs
    # so Moonshine binaries installed by stage 07 can actually run.
    # NOTE: wlr-randr is NOT in the main Gentoo repo (GURU overlay only).
    # It is built from source in stage 06 after emerge finishes.
    # desk.cpl calls it at runtime for display mode control.

    "media-libs/vulkan-loader",     # libvulkan.so for Vulkan rendering
    "media-libs/freetype",          # font rendering
    "media-libs/fontconfig",        # font configuration
    "net-libs/gnutls",              # TLS/crypto (schannel)
    "sys-apps/dbus",                # dynamic device support
    "sys-libs/ncurses",             # terminal / curses support
    "sys-libs/libunwind",           # exception handling / stack unwinding
    "dev-libs/glib",                # GLib (used by various Wine subsystems)
    "media-libs/libglvnd",          # EGL/OpenGL dispatch

    # Audio: PipeWire backend for the YetiOS audio stack (winepipewire.drv).
    # Provides the libpipewire-0.3 pkg-config + headers that
    # dlls/winepipewire.drv links against, plus the runtime daemon that
    # mmdevapi's driver connects to. The `pipewire` USE flag (see make.conf)
    # builds the PipeWire backends/shims on dependent packages.
    "media-video/pipewire",

    # ALSA userland: amixer/alsactl are used by the yetios-audio-init boot
    # service to unmute the HDA codec (fresh ALSA state often comes up muted,
    # which makes PipeWire output silence). Also ships aplay/speaker-test,
    # handy for testing the card directly once a shell exists.
    "media-sound/alsa-utils",

    # Seat management — required by wlroots compositors (frostedglass)
    # to acquire DRM/input device access via libseat.
    "sys-auth/seatd",

    # Realtime scheduling for the audio graph. rtkit is a D-Bus-activated
    # system service that grants RT priority to PipeWire's threads (via
    # polkit authorization of the active local session) without needing
    # per-user rlimits. This is what clears the "RTKit ... ServiceUnknown"
    # warnings and gives glitch-resistant audio under load. polkit comes in
    # as an rtkit dependency; listed explicitly for clarity. Both build
    # against elogind, NOT systemd, because of the global -systemd USE flag.
    # rtkit is D-Bus-activated, so it needs the system bus running — stage 06
    # enables the dbus service for that.
    "sys-auth/rtkit",
    "sys-auth/polkit",

    # ---- Build toolchain (for in-chroot compilation of stages 7+) ----
    # Moonshine, snowcone, snowfall, and frostedglass are all built inside
    # the chroot against the target's libraries to avoid ABI mismatches.
    "sys-devel/gcc",
    "dev-build/make",
    "dev-build/meson",               # meson build system (for wlr-randr)
    "dev-vcs/git",                   # git clone for wlr-randr (hosted on SourceHut)
    "dev-build/autoconf",
    "dev-build/automake",
    "sys-devel/bison",
    "sys-devel/flex",
    "dev-util/pkgconf",
    "sys-kernel/linux-headers",      # DRM headers for snowcone

    # Moonshine (Wine fork) build deps — in addition to runtime deps above
    "media-libs/vulkan-loader",      # (already listed for runtime)
    "dev-libs/libxml2",              # Wine configure
    "media-libs/alsa-lib",           # audio backend
    # media-libs/pipewire (listed above) supplies the headers Moonshine's
    # configure probes for libpipewire-0.3 to build winepipewire.drv.

    # Snowfall build deps (headers for linking)
    # libdrm, libinput, cairo, pam, xkbcommon already listed as runtime deps
    # — their -dev headers are included by Gentoo's default USE flags.

    # Snowcone build deps — just needs DRM headers (linux-headers above)

    # ---- Developer / debug ----
    # foot: lightweight Wayland terminal, opened with Ctrl+T in frostedglass
    # (see fg_input.c). Not an end-user Win32 surface — a dev affordance for
    # running wpctl/amixer/aplay live instead of rebuilding the image per
    # hypothesis. dejavu supplies a monospace font so foot has something to
    # render with (foot's default "monospace" resolves to DejaVu Sans Mono
    # via fontconfig); without any installed font foot won't start.
    "gui-apps/foot",
    "media-fonts/dejavu",

    # Flatpak — runs sandboxed Linux GUI apps (e.g. a browser) independent of
    # the host's library versions. This sits outside the Win32-only surface
    # model, so it's a dev/testing convenience, not a product feature. The
    # Flathub remote is registered in stage 06.
    #
    # xdg-desktop-portal is the portal *framework*. A portal *backend* is
    # deliberately NOT pulled here: the one that implements Settings/FileChooser
    # is sys-apps/xdg-desktop-portal-gtk, which drags in GTK3 — the exact stack
    # going Flatpak let you avoid. Without a backend, flatpak apps still run;
    # they just log the non-fatal "portal.Settings UnknownMethod" warning you
    # already saw and use their own file dialogs. If you later want those
    # portals, add sys-apps/xdg-desktop-portal-gtk (Settings/FileChooser, pulls
    # GTK3) or gui-libs/xdg-desktop-portal-wlr (screencast only; needs
    # compositor protocol support).
    #
    # NB: Flatpak's bwrap sandbox needs unprivileged user namespaces enabled in
    # the kernel. The "CanCreateUserNamespace() clone() failure: EPERM" you saw
    # is a kernel-config/sysctl matter (CONFIG_USER_NS + unprivileged userns),
    # not something a package here can fix — see the note in stage 06.
    "sys-apps/flatpak",
    "sys-apps/xdg-desktop-portal",
]

# ---------------------------------------------------------------------------
# fstab — /boot is the FAT32 ESP.
# ---------------------------------------------------------------------------
FSTAB = """\
# YetiOS fstab — generated by yeti-build.
LABEL=yetios-root  /      ext4   defaults,noatime              0 1
LABEL=YETIOS-ESP   /boot  vfat   defaults,noatime,umask=0077   0 2
proc               /proc  proc   defaults                      0 0
"""

# ---------------------------------------------------------------------------
# First-boot OpenRC service that registers libreldr in UEFI NVRAM.
#
# Why this runs in the guest, not at build time:
#
#   * efibootmgr writes through efivarfs, which only exists when the kernel
#     was itself booted by UEFI firmware. The host's efivarfs (if any)
#     belongs to the host's NVRAM, not the VM's — writing it from the build
#     script would either fail or, worse, register YetiOS's loader on the
#     developer's own machine.
#
#   * The fallback path \\EFI\\BOOT\\BOOTX64.EFI ensures the VM boots even
#     before this service has ever run. After the first successful boot,
#     the firmware menu picks up a proper "LibreLoader (YetiOS)" entry.
#
# The script disables itself once registration succeeds so subsequent boots
# don't keep adding duplicates.
# ---------------------------------------------------------------------------
LIBRELDR_REGISTER_SERVICE = """\
#!/sbin/openrc-run

description="Register LibreLoader (libreldr) in UEFI NVRAM on first boot"

depend() {
    need localmount
    before local
}

start() {
    ebegin "Registering LibreLoader in UEFI boot menu"

    # Only meaningful on UEFI systems.
    if [ ! -d /sys/firmware/efi ]; then
        einfo "Not booted via UEFI; nothing to register."
        rc-update del libreldr-register default 2>/dev/null
        eend 0
        return 0
    fi

    if ! command -v efibootmgr >/dev/null 2>&1; then
        eerror "efibootmgr not installed"
        eend 1
        return 1
    fi

    # Find the disk + partition number that holds the ESP. /boot is the
    # ESP (see fstab). We resolve the mount → device → parent disk so the
    # script works on /dev/sda1, /dev/nvme0n1p1, /dev/vda1 alike.
    esp_dev="$(findmnt -n -o SOURCE /boot)"
    if [ -z "$esp_dev" ]; then
        eerror "Could not determine ESP device for /boot"
        eend 1
        return 1
    fi

    # PKNAME is the parent block device; PARTN is the partition number.
    esp_disk="/dev/$(lsblk -no PKNAME "$esp_dev")"
    esp_part="$(lsblk -no PARTN "$esp_dev" | tr -d ' ')"

    if [ -z "$esp_disk" ] || [ -z "$esp_part" ]; then
        eerror "Failed to resolve ESP disk/partition (dev=$esp_dev)"
        eend 1
        return 1
    fi

    # Skip if an entry with our label already exists.
    if efibootmgr | grep -q "LibreLoader (YetiOS)"; then
        einfo "LibreLoader entry already present; nothing to do."
        rc-update del libreldr-register default 2>/dev/null
        eend 0
        return 0
    fi

    # Single-quoted in bash, so each \\\\ in this Python literal becomes one
    # backslash on disk and is passed verbatim to efibootmgr.
    efibootmgr --create \\
        --disk "$esp_disk" \\
        --part "$esp_part" \\
        --label "LibreLoader (YetiOS)" \\
        --loader '\\EFI\\libreldr\\libreldr.efi'
    rc=$?

    if [ $rc -eq 0 ]; then
        einfo "Registered. Disabling first-boot service."
        rc-update del libreldr-register default 2>/dev/null
    fi
    eend $rc
}
"""

# ---------------------------------------------------------------------------
# OpenRC network configuration for dhcpcd.
#
# Gentoo's OpenRC netifrc setup: /etc/conf.d/net defines how each
# interface is configured, and symlinks in /etc/init.d/ (net.eth0 etc.)
# activate them. For DHCP, the simplest approach is to just enable
# dhcpcd as a global daemon — it will auto-discover all wired interfaces.
#
# We also create a fallback /etc/conf.d/net in case netifrc is present,
# and provide a first-boot service that enables dhcpcd on any interface
# it finds (handles both eth0 and predictable names like enp1s0).
# ---------------------------------------------------------------------------
DHCPCD_CONF = """\
# /etc/dhcpcd.conf — YetiOS defaults

# Don't touch the hostname — keep what we set at build time.
noipv4ll
nohook hostname

# Prefer wired interfaces, timeout quickly so boot isn't slow
# if no cable is plugged in.
timeout 15

# Allow Wine / general networking immediately.
option rapid_commit
option domain_name_servers, domain_name, domain_search
option classless_static_routes
option interface_mtu
"""

# ---------------------------------------------------------------------------
# First-boot Wine configuration service.
#
# On first login, Wine needs to initialise its prefix, download Mono/Gecko,
# and set up the desktop. This service runs once as the yeti user to do
# that initialization with network access available.
# ---------------------------------------------------------------------------
WINE_FIRSTBOOT_SERVICE = """\
#!/sbin/openrc-run

description="First-boot Wine prefix initialization (downloads Mono/Gecko)"

depend() {{
    need net
    after dhcpcd
}}

start() {{
    ebegin "Initializing Wine prefix for {yeti_user}"

    local wine_user="{yeti_user}"
    local wine_home="/home/$wine_user"

    # Skip if Wine prefix already exists and looks initialized
    if [ -f "$wine_home/.wine/system.reg" ]; then
        einfo "Wine prefix already initialized."
        rc-update del wine-firstboot default 2>/dev/null
        eend 0
        return 0
    fi

    # Initialize the Wine prefix — this triggers Mono/Gecko download
    # if the installers aren't already cached.
    su -l "$wine_user" -c "DISPLAY= WAYLAND_DISPLAY= wineboot --init" || true

    # Apply our registry prefs on top
    if [ -f "$wine_home/.frostedglass_prefs.reg" ]; then
        su -l "$wine_user" -c "DISPLAY= WAYLAND_DISPLAY= wine regedit /s $wine_home/.frostedglass_prefs.reg" || true
    fi

    einfo "Wine prefix initialized. Disabling first-boot service."
    rc-update del wine-firstboot default 2>/dev/null
    eend 0
}}
"""

# ---------------------------------------------------------------------------
# Boot-time ALSA mixer initialization.
#
# On a fresh ALSA state the HDA codec frequently comes up with Master/PCM
# muted (or at zero). The PipeWire graph is then perfectly wired and frames
# flow, but the codec emits nothing — i.e. silence with no errors anywhere.
# This service brings the card to a sane, unmuted default BEFORE the
# graphical session (and therefore PipeWire / Moonshine) starts. It runs on
# every boot and persists the result. Safe no-op when no card is present.
#
# NOTE: plain shell braces here — this template is written verbatim (no
# str.format()), unlike WINE_FIRSTBOOT_SERVICE, so braces are NOT doubled.
# ---------------------------------------------------------------------------
ALSA_UNMUTE_SERVICE = """\
#!/sbin/openrc-run

description="Initialize and unmute the ALSA mixer for PipeWire output"

depend() {
    need localmount
}

start() {
    ebegin "Initializing ALSA mixer"

    if [ ! -e /proc/asound/card0 ]; then
        einfo "No ALSA card present; skipping."
        eend 0
        return 0
    fi

    # Bring the codec to its default (unmuted) state per the card's profile.
    alsactl init 2>/dev/null

    # Belt-and-suspenders: explicitly unmute and raise the controls the QEMU
    # HDA codec commonly exposes. Missing controls are ignored.
    for ctl in Master PCM Speaker Headphone Front; do
        amixer -c 0 -q sset "$ctl" unmute 2>/dev/null
        amixer -c 0 -q sset "$ctl" 100% 2>/dev/null
    done

    # Persist so the state survives reboots.
    alsactl store 2>/dev/null

    eend 0
}
"""

# ---------------------------------------------------------------------------
# Package-specific USE flags
# ---------------------------------------------------------------------------
PORTAGE_FREETYPE_USE = "media-libs/freetype harfbuzz\n"
